version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    links:
      - database:database
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py db_setup &&
             python manage.py create_teacher owner test@example.com test1234 &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
